version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59-neon
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
        - grid
  chrome:
    image: selenium/node-chrome:3.141.59-neon
    container_name: node-chrome
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
    networks:
        - grid    
  firefox:
    image: selenium/node-firefox:3.141.59-neon
    container_name: node-firefox
    ports:
      - "5901:5900"
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=10
      - NODE_MAX_SESSION=10
    networks:
        - grid
networks:
    grid: 
      driver: bridge